name: frame_gemini_chat_text
description: "Speak to a Gemini AI model by voice using platform-provided speech-to-text, and show response text in any language on the Brilliant Labs Frame display"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.32.12
  flutter_chat_types: ^3.6.2
  flutter_chat_ui: ^1.6.15
  google_generative_ai: ^0.4.6
  image: ^4.2.0
  logging: ^1.2.0
  shared_preferences: ^2.3.2
  simple_frame_app:
    path: ../simple_frame_app
  speech_to_text: ^7.0.0
  uuid: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - packages/simple_frame_app/lua/battery.min.lua
    - packages/simple_frame_app/lua/code.min.lua
    - packages/simple_frame_app/lua/data.min.lua
    - packages/simple_frame_app/lua/sprite.min.lua
    - packages/simple_frame_app/lua/text_sprite_block.min.lua
    - assets/frame_app.min.lua
